# Branch definition: only build master and PRs
branches:
  only:
    master

# Build definition; language, deps, scripts
language: python
python:
  - "3.5"
install:
  - pip install -r requirements/dev.txt
  - pip install coveralls
script:
  - tox
after_success:
  - coveralls
  - coverage erase
